#!/usr/bin/env python

import subprocess

if __name__ == '__main__':
    state = int(subprocess.check_output("synclient \
            | grep TouchpadOff \
            | tr -s ' ' \
            | cut -d ' ' -f 4", shell=True).strip())

    # set new state, TouchpadOff = {0..2}
    new_state = (state + 1) % 3
    subprocess.call(["synclient", "TouchpadOff={}".format(new_state)])

